# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controllingpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 359)
        self.servoonoff = QtWidgets.QPushButton(Dialog)
        self.servoonoff.setGeometry(QtCore.QRect(30, 30, 111, 111))
        self.servoonoff.setStyleSheet("font: 12pt \"MS Gothic\";")
        self.servoonoff.setObjectName("servoonoff")
        self.initial = QtWidgets.QPushButton(Dialog)
        self.initial.setGeometry(QtCore.QRect(30, 150, 111, 81))
        self.initial.setStyleSheet("font: 12pt \"MS Gothic\";")
        self.initial.setObjectName("initial")
        self.designatedlocation = QtWidgets.QPushButton(Dialog)
        self.designatedlocation.setGeometry(QtCore.QRect(250, 240, 131, 81))
        self.designatedlocation.setStyleSheet("font: 12pt \"MS Gothic\";")
        self.designatedlocation.setObjectName("designatedlocation")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 240, 211, 81))
        self.lineEdit.setStyleSheet("font: 16pt \"Cambria Math\";")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 30, 231, 111))
        self.label.setStyleSheet("background-color: rgb(64, 224, 208);\n"
"font: 24pt \"MS UI Gothic\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 150, 231, 81))
        self.pushButton_4.setStyleSheet("font: 12pt \"MS Gothic\";")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.servoonoff.setText(_translate("Dialog", "SERVO ON"))
        self.initial.setText(_translate("Dialog", "原點復歸"))
        self.designatedlocation.setText(_translate("Dialog", "指定位置GO"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "在這裡輸入位置"))
        self.label.setText(_translate("Dialog", "STATUS: OFF"))
        self.pushButton_4.setText(_translate("Dialog", "只是用來填滿版面的按鈕"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
