# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'additionandsubtract.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1103, 798)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(270, 230, 201, 51))
        self.lineEdit.setStyleSheet("font: 24pt \"Cambria Math\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(500, 230, 21, 61))
        self.label.setStyleSheet("font: 24pt \"Adobe Devanagari\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(470, 300, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.total = QtWidgets.QLabel(Dialog)
        self.total.setGeometry(QtCore.QRect(270, 350, 481, 61))
        self.total.setStyleSheet("font: 36pt \"Cambria Math\";")
        self.total.setObjectName("total")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 200, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(550, 230, 201, 51))
        self.lineEdit_2.setStyleSheet("font: 24pt \"Cambria Math\";")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setText(_translate("Dialog", "0"))
        self.lineEdit_2.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "+"))
        self.pushButton.setText(_translate("Dialog", "計算！"))
        self.total.setText(_translate("Dialog", "答案會從這裡憑空出現"))
        self.pushButton_2.setText(_translate("Dialog", "加減轉換"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
